name: Test manual dispatch

on:
  workflow_dispatch:

jobs:
  print_commit_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print commit SHA & Workflow ID
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.sha }}"
          echo "Workflow run ID: ${{ github.run_id }}"

      - name: Find current PR number
        uses: jwalton/gh-find-current-pr@v1
        id: pr-finder

      - name: Echo PR number
        run: |
          echo "PR number: ${{ steps.pr-finder.outputs.pr }}"