name: Test Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      choice_name:
        description: 'Select an action'
        required: true
        default: 'Option1'
        type: choice
        options:
          - Option1
          - Option2
          - Option3

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print commit SHA
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.sha }}"
          echo "Workflow run ID: ${{ github.run_id }}"

      - name: Find current PR number
        uses: jwalton/gh-find-current-pr@v1
        id: pr-finder

      - name: Echo PR number
        run: |
          echo "PR number: ${{ steps.pr-finder.outputs.pr }}"

      - name: Print the selected choice
        run: |
          echo "You selected: ${{ github.event.inputs.action }}"